classes = {"NKK": "https://www.classnk.or.jp/register/regships/regships.aspx",
           "NV": "https://vesselregister.dnv.com/vesselregister/vesselregister.html",
           "BV": "https://marine-offshore.bureauveritas.com/bv-fleet/#/bv-fleet/",
           "LRS": "https://www.lr.org/",
           "ABS": "https://ww2.eagle.org/",
           "RINA": "https://www.rina.org/",
           "CCS": "https://mail.ccs.org.cn/",
           "KR": "https://www.krs.co.kr/eng/ship_as_address/regist_search.aspx?s_code=0103040500",
           "RMRS": "https://rs-class.org/",
           "IRS": "https://www.irclass.org/",
           "PRS": "https://www.prs.pl/",
           "CRS": "http://www.crs.hr/",
           "GL": "https://www.dnv.com/"}
